### ISSUE TITLE
ade4 function fourthcorner

### ISSUE THREAD

**Issue by beausoleilmo** [sdray/ade4#1]
When running the fourthcorner example in the description file, it gives me a graph without the black tiles. 
![plot_zoom_png](https://cloud.githubusercontent.com/assets/15717151/11543590/8e3196d2-990b-11e5-932d-20a9263041df.png)

I think it's suppose to look like this example [here](http://pbil.univ-lyon1.fr/ade4/ade4-html/fourthcorner.html) from pbil.univ-lyon1.fr website. Do you have any idea?

Thanks,

**Comment by sdray** [comment]
Hi.

Do not worry, your results are correct. The examples on pbil have not 
been updated and use an older version of ade4. In the new version, the 
test is performed with the sequential procedure proposed by ter Braak et 
al (2012) which provides correct type I error.

I will update the ade4 website on pbil.

Cheers

Le 02/12/2015 21:46, beausoleilmo a écrit :
>
> When running the fourthcorner example in the description file, it 
> gives me a graph without the black tiles.
> plot_zoom_png 
> <https://cloud.githubusercontent.com/assets/15717151/11543590/8e3196d2-990b-11e5-932d-20a9263041df.png>
>
> I think it's suppose to look like this example here 
> <http://pbil.univ-lyon1.fr/ade4/ade4-html/fourthcorner.html> from 
> pbil.univ-lyon1.fr website. Do you have any idea?
>
> Thanks,
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sdray/ade4/issues/1>.
>


-- 
Stéphane DRAY (stephane.dray@univ-lyon1.fr)
Laboratoire BBE-CNRS-UMR-5558, Univ. C. Bernard - Lyon I
43, Bd du 11 Novembre 1918, 69622 Villeurbanne Cedex, France
Tel: 33 4 72 43 27 57       Fax: 33 4 72 43 13 88
http://pbil.univ-lyon1.fr/members/dray/

**Comment by beausoleilmo** [comment]
Thanks!
