### ISSUE TITLE
Slight error in code of plot.foucart?

### ISSUE THREAD

**Issue by DPlat** [sdray/ade4#13]
Hello,
If I understand it correctly, unexported function plot.foucart() begins with the concatenation in object _cootot_ of the various projections returned by foucart(), the goal being to create an encompassing background for subsequent plots:
```
cootot <- x$li[, c(xax, yax)]
auxi <- x$li[, c(xax, yax)]
names(auxi) <- names(cootot)
cootot <- rbind.data.frame(cootot, auxi)
auxi <- x$Tli[, c(xax, yax)]
names(auxi) <- names(cootot)
cootot <- rbind.data.frame(cootot, auxi)
auxi <- x$Tco[, c(xax, yax)]
names(auxi) <- names(cootot)
cootot <- rbind.data.frame(cootot, auxi)
```
In this case, I believe that line 2 of the above code should rather be:
`auxi <- x$co[, c(xax, yax)]`
If I am wrong, I apologize in advance.
Cheers,
Didier Plat

**Comment by thioulouse** [comment]
Yes, you are right and the same problem exists in adegraphics:::plot.foucart. I am going to fix it.
Thanks for letting us know.
