### ISSUE TITLE
Error in `[.data.frame`(dfxy, , yax) : undefined columns selected

### ISSUE THREAD

**Issue by panbbq** [sdray/ade4#17]
Hello,
my code is followed:
>   obs.pca=dudi.pca(data.frame(dat), scannf=F, nf=10)
>   dat_cluster = pam(dat_dist[[i]], k = 2)$cluster
>   obs.bet=bca(obs.pca, fac=as.factor(dat_cluster), scannf=F, nf=k-1)
>   s.class(obs.bet$ls, fac=as.factor(dat_cluster), grid=F)

I want to use `bca` and `s.class` to show cluster 2, why it can't work .
Perhaps I don't know the principle of `bca`, would you mind explaning simply?

**Comment by sdray** [comment]
Hi,
hard to understand without any error message. Note that if you have only 2 groups, the outputs are only represented in 1 dimension. In this case, the s.class function is not adapted (it draws on 2D) and you should use the s1d.class function (from adegraphics) or sco.class (from ade4).

Cheers

**Comment by panbbq** [comment]
Hi again,
So 2 groups couldn’t be shown on 2D with bca’output while it can be shown on 2D using pca’result?
Thanks


发自我的 iPad

------------------ Original ------------------

**Comment by sdray** [comment]
Yes. Because PCA is the analysis of the individuals x variables table while BCA is the PCA of the groups x variables table (with the means per group per variable in the table). Hence the rank of the matrix is different between the two analyses leading to a different number of dimensions 

Cheers

**Comment by panbbq** [comment]
Thanks,
I know little about bca, would you mind recommending some article to me？Better have pdf.Words can hardly express my gratitude!
Best wishes!




 
---Original---

**Comment by sdray** [comment]
You can have a look to this course https://pbil.univ-lyon1.fr/R/pdf/course4.pdf
An example of the use of BCA in the context of spatial analysis can be found in section 3.1 of http://pbil.univ-lyon1.fr/members/dray/files/articles/dray2011b.pdf

Original papers are in french. Note also that our book (https://www.springer.com/gp/book/9781493988488) has a chapter describing BCA and associated methods
