### ISSUE TITLE
Remove extraneous parentheses causing compiler warning

### ISSUE THREAD

**Issue by proebuck** [sdray/ade4#2]
Please address Clang complaint:

```bash
gcc -arch x86_64 -std=gnu99 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include    -fPIC  -mtune=core2 -g -O2  -c fourthcorner.c -o fourthcorner.o
fourthcorner.c:1662:21: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
      if ((*typeTest==3)){
           ~~~~~~~~~^~~
fourthcorner.c:1662:21: note: remove extraneous parentheses around the comparison to silence this warning
      if ((*typeTest==3)){
          ~         ^  ~
fourthcorner.c:1662:21: note: use '=' to turn this equality comparison into an assignment
      if ((*typeTest==3)){
                    ^~
                    =
1 warning generated.
```

**Comment by proebuck** [comment]
Notice this was fixed here a couple months back, but never released.
Please release "ade4_1.7-4" and make the updated package available on CRAN.

**Comment by sdray** [comment]
Yes. Sorry I did not answered to your comment but did the correction.

We will upload soon a new version on CRAN.

Cheers

**Comment by proebuck** [comment]
You closed this issue without providing a new GitHub release. Nothing new on CRAN yet either.
Please reopen this until the fix is **actually** released.

**Comment by sdray** [comment]
done !

**Comment by sdray** [comment]
ade4 1.7-4 that corrects this issue is now on CRAN.

so I can close the issue now ;-)
