### ISSUE TITLE
plot of function s.class to add x and y axis, title ... 

### ISSUE THREAD

**Issue by xndless** [sdray/ade4#23]
I didn't find a way to do it.

**Comment by aursiber** [comment]
Hi,
The `adegraphics` package, a graphical package, is suitable to display `ade4` outputs and customize the graphs. To add axes and title, you can see this example:
```
library(adegraphics)
xy <- cbind.data.frame(x = runif(200, -1, 1), y = runif(200, -1, 1))
posi <- factor(xy$x > 0) : factor(xy$y > 0)
s.class(xy, fac = posi, paxis.draw = TRUE, main = "Main title")
```

See the package [vignette](https://cran.r-project.org/web/packages/adegraphics/vignettes/adegraphics.html) and the Chapter 4 of the [ade4 book](https://www.springer.com/gp/book/9781493988488) to begin with `adegraphics`.

**Comment by sdray** [comment]
A small correction: it is `paxes.draw`, not `paxis.draw`. To display labels for x and y axes use `xlab` and `ylab` arguments:

`s.class(xy, fac = posi, paxes.draw = TRUE, main = "Main title", xlab = "x label", ylab = "y label")`
