### ISSUE TITLE
one-liner warning

### ISSUE THREAD

**Issue by SamGG** [sdray/ade4#24]
Hi,
Might it be possible to have a one-liner warning?
```
 warning("The use of the 'suprow.dudi' method requires that the ",
         "supplementary table has been transformed as the original table") 
```
https://github.com/sdray/ade4/blob/28b0cdeaa32fb2467e1013816273e03d29b40816/R/suprow.R#L38-L39
Best

**Comment by aursiber** [comment]
Updated in c070e1c128102f01bf09da29bd0476afdad6b673

**Comment by SamGG** [comment]
Merci.
