### ISSUE TITLE
dist.ktab() returns different result than one would expect for fuzzy coded traits

### ISSUE THREAD

**Issue by KunzstLD** [sdray/ade4#26]
Hi, 
I'm not sure if this is the right place to post this but I noticed when calculating distances between fuzzy coded traits with *dist.ktab* that the result one obtains is different than what one would expect (based on the formulas given in the documentation and the definition of the functions). 
According to the *dist.ktab()* function definition, the *Overlap index Manly* is used by default for fuzzy coded variables (line 74, *methodF <- 2*). To calculate distances in *dist.ktab()* the function *dist.prop()* is used. According to the *dist.prop()* function definition *method = 2* applies *fun2*, which is defined as: 

```{r}
1 - sum(p * q) / sqrt(sum(p * p)) / sqrt(sum(q * q))
```

Using a small made up example: 

```{r}
# example data with two fuzzy coded traits (T and Y)  
trait_matrix <-
  data.frame(
    "T_1" = c(0.5, 0.2),
    "T_2" = c(0.5, 0.6),
    "T_3" = c(0, 0.2),
    "Y_1" = c(0.1, 1),
    "Y_2" = c(0.9, 0),
    row.names = c("A", "B")
  )
# Overlap index manly
fun_overlap_ind <-
  function(p, q) {
    1 - sum(p * q) / sqrt(sum(p * p)) / sqrt(sum(q * q))
  }

# Calculating "manually" distance between Taxa "A" and "B" based on trait T
val_1 <- fun_overlap_ind(p = trait_matrix[1, 1:3],
                                         q = trait_matrix[2, 1:3])
# Calculating "manually" distance between Taxa "A" and "B" based on trait Y
val_2 <- fun_overlap_ind(p = trait_matrix[1, 4:5],
                                         q = trait_matrix[2, 4:5])

# Total distance between A and B based on both traits: 0.5183828 
mean(c(val_1, val_2))
```

Now with the ade4 package:

```{r}
# calculate via ade4 package:
vec <- sub("\\_.*", "\\1", names(trait_matrix))
blocks <- rle(vec)$lengths
dat <- prep.fuzzy(trait_matrix, blocks)
dat <- ktab.list.df(list(dat))

# Total distance between A and B based on both traits: 0.7199881  
dist.ktab(dat, type = "F", scann = FALSE)
```

I noticed that the result obtained from *dist.ktab* is actually the square root (sqrt) of the result of the "manual" calculation.

```{r}
sqrt(mean(c(val_1, val_2)))
```

This seems not to be a coincidence. One could just calculate the distances for one of the traits T or Y and the result from ade4 would be again the sqrt of the result from the "manual" calculation. 
First of all, trying to understand the code behind the function did not reveal that the sqrt was taken at the end, but maybe I missed something. This also seems not to be stated in the documentation. Secondly,  why is the square root taken in the end? 
This is not a rant or something, I'm thankful for the great package but I think the documentation could be improved here.

**Comment by aursiber** [comment]
Hi,
This is the best place to post this! 
I forward here the answer that Sandrine Pavoine, the author of the function `dist.ktab`, makes about your post:

_Thank you for your message. You are right: the average dissimilarity is square rooted at the end. As indicated in the manual the function calculates the "mixed-variables coefficient of distance" developed by Pavoine et al. (2009). The full reference is given in the manual of the function. The coefficient is fully explained in this paper. As explained in the paper, the square root is used to obtain Euclidean properties for the dissimilarities at least in absence of missing data. Please have a full read to this paper to know more about the mixed-variables coefficient of distance._

**Comment by KunzstLD** [comment]
Hi, 
thanks for your and Sandrine's reply! Good to know that everything is described in the manual of the function given in the SI in Pavoine et al. (2009). However, the link provided in the paper to the SI is not working for me (Access denied from Oikos). Not sure if this is just the case for me or also for others.
Is it possible to make the manual for the `dist.ktab` function accessible for everybody?

**Comment by thioulouse** [comment]
Hi

The link provided in the paper is indeed dead. A direct link to the appendix of the paper could be added somewhere:

http://www.oikosjournal.org/sites/oikosjournal.org/files/appendix/o16668.pdf
http://www.oikosjournal.org/sites/oikosjournal.org/files/appendix/o16668_files.zip

Maybe in the .Rd file of the dist.ktab function ?

Jean

**Comment by aursiber** [comment]
Good idea ! Thanks Jean.
I just updated the help page of the dist.ktab function.

**Comment by KunzstLD** [comment]
Thanks a lot for the link and the update of the help page!
