### ISSUE TITLE
Install of ADEGraphics failed - for R installed via Homebrew on macOS

### ISSUE THREAD

**Issue by R1-Globulo** [sdray/ade4#33]
Good evening, 

I just tried to change my setup and used Homebrew on MacOS to install all R-related installs.
However, what 

`install.packages("adegraphics")`

Unfortunately that led to the following - a few packages that cannot be installed it seems...

Any thoughts?

```
ERROR: compilation failed for package ‘RcppArmadillo’
* removing ‘/opt/homebrew/lib/R/4.2/site-library/RcppArmadillo’
ERROR: dependencies ‘deldir’, ‘RcppEigen’ are not available for package ‘interp’
* removing ‘/opt/homebrew/lib/R/4.2/site-library/interp’
ERROR: dependency ‘RcppArmadillo’ is not available for package ‘ade4’
* removing ‘/opt/homebrew/lib/R/4.2/site-library/ade4’
ERROR: dependency ‘interp’ is not available for package ‘latticeExtra’
* removing ‘/opt/homebrew/lib/R/4.2/site-library/latticeExtra’
ERROR: dependencies ‘ade4’, ‘latticeExtra’ are not available for package ‘adegraphics’
* removing ‘/opt/homebrew/lib/R/4.2/site-library/adegraphics’
```

Thanks a lot!

E.

**Comment by thioulouse** [comment]
Is there any good reason to install R via Homebrew on a Mac ?

**Comment by R1-Globulo** [comment]
That is a good question - I actually had R installed 'in the normal way' - and everything was fine regarding the installation of ade4 and ADEgraphics. So, yes... but why not? 

That way I get all my apps and programs under the same roof, so to speak, and get updates regularly and consistently all at once, no? 

What do you reckon?

E.

**Comment by thioulouse** [comment]
The main problem is that Homebrew and CRAN binaries are not compatible. This means that you cannot use the command install.packages("adegraphics"). You need to compile the packages you want to install, so you should use install.packages("adegraphics", type="source"). And of course you also need to compile all the packages on which the package you want to install depends. And all the needed libraries should be installed in your Homebrew config. I guess that this is the biggest problem you will have if you really want to use R with Homebrew, and why this is not the recommended way.

**Comment by R1-Globulo** [comment]
I have to admit that I am not very familiar with what happens "behind the scene" when we install a package... So, by the sound of it, it sounds like a bit of a nightmare, or at least, quite a cumbersome process, if I wanted to make everything work under a Homebrew install. 

I thought that would lead to a very simple setup - everything in one place and easy to manage, but it sounds that it is actually not the case! 

So, I might actually follow your advice and write the dreaded 

`brew uninstall r`

and reinstall it via the usual installer from CRAN.

Thank you for your advice.
E.

**Comment by R1-Globulo** [comment]
By the way (last comment) - I intend to use R within a Jupyter Notebook, via the ÌRKernel`package, which should make it an option to select from in the drop down list of kernels in the notebook. 

I also do have Python kernels derived from virtual environments in that list. 
Of course the R one is just linking to the standard install - nothing virtual in that! 

Is that a very strange setup , you reckon?

Thanks 
E.

**Comment by thioulouse** [comment]
I don't use Jupyter or Python, so I can't say if this is weird or not. But the main thing is that it does what you want it to do.
