### ISSUE TITLE
Problem using newick2phylog

### ISSUE THREAD

**Issue by p-neves** [sdray/ade4#34]
HI:
I have a phylo class object obtained using taxize's class2tree function (the attached file is an gzip-compressed RDS) and i'd like to use ade4::newick2phylog on this object.

I first use `Tree <- ape::write.tree(tr$phylo)` to write the tree to a file and then try to write a phylogeny using

 `newick2phylog(Tree)`, but I get the following error:

`Error in dimnames(w1) <- list(leave.names, names(x1)) : 
  length of 'dimnames' [2] not equal to array extent`

Any opinions on why this happens and how to fix it?

Thanks in advance:

Pedro

[TreePN.gz](https://github.com/sdray/ade4/files/10976947/TreePN.gz)

**Comment by sdray** [comment]
Hi Pedro,
The phylog class is a little bit outdated and this can explain the issue. Could you tell me which type of analysis you want to perform so that I can help you to find an alternative way (we re-implemented some methods in adephylo that use phylo / phylo4 classes instead of phylo to manage phylogentic trees).

**Comment by p-neves** [comment]
Hi Stéphane:

Thanks for you help. Right now I'm experimenting with [hillR](https://github.com/daijiang/hillR) and trying to implement "their" framework for partitioning diversity into its facets and components.

It so happens that their code resorts to write.tree (from ape) and newick2phylog to compute the phylogenetic diversity. All this is still a bit new to me, as before I was using the rao function from De Bello, 2010 (doi: 10.1111/j.1654-1103.2010.01195.x)....

**Comment by sdray** [comment]
OK. I think that you just need to update `hillR` as it is indicated in the [NEWS](https://github.com/daijiang/hillR/blob/454bce75a82e6ce8b7f0e1a219c3a0d29324c13f/NEWS.md) that `newick2phylog`  is no longer used since version 0.5.0

Cheers

**Comment by p-neves** [comment]
I've upgraded it, but now I get another error:

`Error in comm[, tree$tip.label] : incorrect number of dimensions`. 

I'll keep looking anyway.

**Comment by sdray** [comment]
I think that now the problem is not related to `ade4`. Pehaps you could contact the developper of `hillR`  to ask for some help.

**Comment by p-neves** [comment]
No. The problem is much simpler, I think. From what I've seen is just a mismatch in the species names between the 2 objects (community data and phylo tree). I'm sure I'll fix it.

Thanks for your help anyway
