### ISSUE TITLE
Feature request: display function call for dudi creation after user selects nf

### ISSUE THREAD

**Issue by zkamvar** [sdray/ade4#8]
Hello,

I have a proposition to display a helper message after the user selects the number of axes:

```
> data(deug)
> deug.dudi <- dudi.pca(deug$tab, center = deug$cent, scale = FALSE)
Select the number of axes: 
2

You can reproduce this result with the following command:
deug.dudi <- dudi.pca(deug$tab, center = deug$cent, scale = FALSE, scannf = FALSE, nf = 2L)

> 
```

I've noticed that many users understand why they are being asked to select a number of axes, but do not know how to tell ade4 to automatically select the desired number of axes. This results in a lot of frustration when the analyses have to be redone. 

By displaying this message, I hope to alleviate some of these frustrations.

I'll submit a PR on this soon, hopefully.

-Zhian

**Comment by sdray** [comment]
Hi,

thanks for the proposition. I think that it could be possible to do it by modifying the as.dudi function and writing the text by using the information contained the the 'call' argument. Cheers.

**Comment by aursiber** [comment]
Feature added on bc3382565c6f141222fd1379bb6948ad4ae1f078
