### ISSUE TITLE
suprow pour dudi.fca

### ISSUE THREAD

**Issue by martialferreol** [sdray/ade4#9]
Bonjour Stéphane,
un de mes collègues a un souci avec la fonction suprow utilisé sur une fca.
il semble avoir un souci avec les pondérations.
aussi j'ai bricolé un petit correctif "sur le tas". je te le soumet donc.

Bonne journée

Martial Ferréol

[suprowfca.txt](https://github.com/sdray/ade4/files/1783888/suprowfca.txt)

**Comment by sdray** [comment]
Hi Martial,

Thanks for the suggestion. I just added a new method suprow.fca in ade4. Now

suprow(d1,w2)$lisup

should work.

Cheers

PS: en anglais pour Github ;-)
